### PR TITLE
comment out travis testing on release

### PR DESCRIPTION
**Pull request by tkelman**
not supported according to REQUIRE

### CODE REVIEW

**Comment by Keno** [comment]
Thanks.

**Comment by tkelman** [comment]
test failure expected?

**Comment by Keno** [comment]
Ish, there's one regression which I need to get around to investigating, but haven't gotten to yet.

**Comment by tkelman** [comment]
and looks like REQUIRE should add Colors, FixedPointNumbers
and test/REQUIRE should add Gadfly, Compose?

**Comment by Keno** [comment]
Colors and FixedPointNumbers are really only required by virtue of the dependency on VT100, but I'm fine with adding them explicitly.

**Comment by tkelman** [comment]
If VT100 will absolutely always depend on both then it's not strictly needed, but I like being explicit with anything you do `using` or `import` on to ensure it will be there

**Pull request merged**
